#!/usr/bin/env python3

from bs4 import BeautifulSoup
import requests

a = sys.argv

if len(a) == 0:
    print("Missing url")
    exit()

domain = sys.argv[1]

if 'https' not in domain:
    if 'http' in domain:
        domain.replace('http', 'https')
    else:
        domain = 'https://' + domain

page = requests.get(domain)
soup = BeautifulSoup(page.text, features="lxml")

icon_link = soup.find("link", rel="shortcut icon")

if icon_link is None:
    icon_link = soup.find("link", rel="icon")

if icon_link is None:
    print(domain + '/favicon.ico')
    exit()

url = icon_link["href"]

if (url.startswith('/')):
    url = domain + url

print(url)
